version: '3'

services:
  springboot-docker-compose-app-container:
    image: neutralizer-test/quote-manipulator-dockerize-maven:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:5.4.3
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    expose:
      - "3306"

  elk:
    image: neutralizer-test/elk
    build:
      context: ./elk
      dockerfile: Dockerfile-elk
    ports:
      - "5601:5601"
      - "9200:9200"


  #5601 (Kibana web interface).
  #9200 (Elasticsearch JSON interface).
  #5044 (Logstash Beats interface, receives logs from Beats such as Filebeat – see the Forwarding logs with Filebeat section).
  #The image also exposes Elasticsearch's transport interface on port 9300
#  elk:
#    image: sebp/elk
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5044:5044"
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
#    ports:
#      - "9200:9200"
#    environment:
#      - "xpack.security.enabled=false"
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:5.4.0
#    ports:
#      - "5601:5601"
#    environment:
#      - "xpack.security.enabled=false"
#    depends_on:
#      - elasticsearch
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:5.4.0
#    ports:
#      - "25826:25826"
#    volumes:
#      - $PWD/elk-config:/elk-config
#    command: logstash -f /elk-config/logstash-tcp-input.conf
#    depends_on:
#      - elasticsearch