version: '3'

services:
  springboot-docker-compose-app-container:
    image: neutralizer-test/quote-manipulator-dockerize-maven:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.4.3
    depends_on:
      - prometheus
    ports:
      - 3000:3000


