version: '3'

services:
  springboot-docker-compose-app-container:
    image: neutralizer/quote-manipulator-dockerize-maven:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:5.4.3
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    expose:
      - "3306"

  #5601 (Kibana web interface).
  #9200 (Elasticsearch interface).
  elk:
    image: neutralizer/elasticsearch-logstash-kibana
    build:
      context: ./elk
      dockerfile: Dockerfile-elk
    ports:
      - "5601:5601"
      - "9200:9200"